import Image from "next/image";
import { Container } from "@/components/ui/Container";
import { Reveal } from "@/components/motion/Reveal";

/**
 * The strip's repeating unit: four columns alternating between a full-height
 * photograph and a stacked pair. The 48,000 tile is what keeps this from
 * reading as a stock-photo wall.
 *
 * Square corners are the one radius exception on the page. The tiles butt
 * edge to edge, and any rounding would read as a gap. See design-system.md 1.5.
 */
type Tile =
  | { kind: "photo"; src: string; alt: string; w: number; h: number }
  | { kind: "data" };

const COLUMNS: Tile[][] = [
  [
    { kind: "data" },
    {
      kind: "photo",
      src: "/assets/ui/img/gallery-bruges.jpg",
      alt: "Stepped gable houses along a canal at dusk.",
      w: 600,
      h: 450,
    },
  ],
  [
    {
      kind: "photo",
      src: "/assets/ui/img/gallery-coast.jpg",
      alt: "A tidal pool below a cliff at sunset, its wall covered in graffiti.",
      w: 1200,
      h: 628,
    },
  ],
  [
    {
      kind: "photo",
      src: "/assets/ui/img/gallery-truck.jpg",
      alt: "A turquoise pickup truck parked under a filling station canopy.",
      w: 482,
      h: 600,
    },
    {
      kind: "photo",
      src: "/assets/ui/img/gallery-crowd.jpg",
      alt: "A performer lit in violet on a club stage.",
      w: 1200,
      h: 1800,
    },
  ],
  [
    {
      kind: "photo",
      src: "/assets/ui/img/gallery-snow.jpg",
      alt: "A track through snow-covered pines.",
      w: 600,
      h: 840,
    },
  ],
];

function DataTile() {
  return (
    <div className="bg-surface flex h-full min-h-[150px] flex-col items-center justify-center px-6 text-center">
      <p className="text-lime text-[30px] leading-none font-medium">48,000</p>
      <p className="text-text-3 mt-3 max-w-[20ch] text-[11px] leading-[1.6] font-medium tracking-[0.12em] uppercase">
        Images generated by artificial intelligence
      </p>
    </div>
  );
}

/**
 * Gaps are margins rather than flex `gap`, so that two passes of this track
 * measure exactly twice one pass and the -50% loop lands seamlessly.
 */
function Track({ hidden = false }: { hidden?: boolean }) {
  return (
    <>
      {COLUMNS.map((column, ci) => (
        <div
          key={ci}
          aria-hidden={hidden || undefined}
          className="mr-1 flex w-[220px] shrink-0 flex-col gap-1 sm:w-[280px] lg:w-[340px]"
        >
          {column.map((tile, ti) =>
            tile.kind === "data" ? (
              <div key={ti} className="min-h-0 flex-1">
                <DataTile />
              </div>
            ) : (
              <Image
                key={ti}
                src={tile.src}
                alt={hidden ? "" : tile.alt}
                width={tile.w}
                height={tile.h}
                className="min-h-0 w-full flex-1 object-cover"
              />
            ),
          )}
        </div>
      ))}
    </>
  );
}

export function Gallery() {
  return (
    <section aria-labelledby="gallery-title" className="pb-24 md:pb-32">
      <Container>
        <Reveal>
          <h2
            id="gallery-title"
            className="text-text text-[clamp(26px,4vw,34px)] leading-[1.4] tracking-[-0.01em]"
          >
            Journey Through Art of community
          </h2>
        </Reveal>
      </Container>

      {/* Full bleed, past both viewport edges. */}
      <div className="group mt-10 overflow-hidden">
        <div className="flex h-[420px] w-max motion-safe:animate-(--animate-drift) motion-safe:group-hover:[animation-play-state:paused] md:h-[520px]">
          <Track />
          {/* The second pass is what makes the loop seamless. It carries no
              information, so it is hidden from assistive technology. */}
          <Track hidden />
        </div>
      </div>
    </section>
  );
}
